error handling

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -3,6 +3,7 @@
 # --------------
 ROOT_HOME=/var/root
 DOT_HOME=~/dotfiles
+VIMPLUG_FILE=~/.vim/autoload/plug.vim
 ZPLUG_HOME=~/.zplug
 TPM_HOME=~/.tmux/plugins/tpm
 REMOTE_URL="https://github.com/vwrs/dotfiles.git"
@@ -68,30 +69,54 @@ download() {
     if has "git"; then
       git clone --recursive $REMOTE_URL $DOT_HOME
     else
-      echo "${RED}Please install git.${NORMAL}"
+      echo "${RED}Please install git.$NORMAL"
       exit 1
     fi
-    echo "${GREEN}Successfully downloaded dotfiles. ✔︎ ${NORMAL}"
+    if [ $? = 0 ]; then
+      echo "${GREEN}Successfully downloaded dotfiles. ✔︎ $NORMAL"
+    else
+      echo "${RED}An unexpected error occurred when trying to install git.$NORMAL"
+      exit 1
+    fi
   else
-    echo "${BOLD}dotfiles already exists.${NORMAL}"
+    echo "${BOLD}dotfiles already exists.$NORMAL"
   fi
-  # install vim-plug
-  # curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+  # vim-plug
+  if [ ! -f $VIMPLUG_FILE ]; then
+    echo "Dowloading vim-plug ..."
+    curl -fLo $VIMPLUG_FILE --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+    if [ $? = 0 ]; then
+      echo "${GREEN}Successfully downloaded vim-plug at $VIMPLUG_FILE. ✔︎ $NORMAL"
+    else
+      echo "${RED}An unexpected error occurred when trying to install vim-plug.$NORMAL"
+      exit 1
+    fi
+  fi
   # zplug
   if [ ! -d $ZPLUG_HOME ]; then
     echo "Downloading zplug ..."
     curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
-    echo "${GREEN}Successfully downloaded zplug in ${ZPLUG_HOME}. ✔︎ ${NORMAL}"
+    if [ $? = 0 ]; then
+      echo "${GREEN}Successfully downloaded zplug in ${ZPLUG_HOME}. ✔︎ $NORMAL"
+    else
+      echo "${RED}An unexpected error occurred when trying to install zplug.$NORMAL"
+      exit 1
+    fi
   else
-    echo "${BOLD}zplug already exists.${NORMAL}"
+    echo "${BOLD}zplug already exists.$NORMAL"
   fi
   # tpm
   if [ ! -d $TPM_HOME ]; then
     echo "Downloading tpm ..."
     git clone https://github.com/tmux-plugins/tpm $TPM_HOME
-    echo "${GREEN}Successfully downloaded tpm in ${TPM_HOME}. ✔︎ ${NORMAL}"
+    if [ $? = 0 ]; then
+      echo "${GREEN}Successfully downloaded tpm in $TPM_HOME. ✔︎ $NORMAL"
+    else
+      echo "${RED}An unexpected error occurred when trying to install tpm.$NORMAL"
+      exit 1
+    fi
   else
-    echo "${BOLD}tpm already exists.${NORMAL}"
+    echo "${BOLD}tpm already exists.$NORMAL"
   fi
 }
 
@@ -113,8 +138,13 @@ symlink_files() {
     # symlink files
     ln -snfv $DOT_HOME/$f $1/$f
   done
-  echo "${GREEN}Successfully symlink dotfiles. ✔︎ ${NORMAL}"
-  echo "${BOLD}To enable zsh, please execute 'chsh'.${NORMAL}"
+  if [ $? = 0 ]; then
+    echo "${GREEN}Successfully symlink dotfiles. ✔︎ $NORMAL"
+  else
+    echo "${RED}An unexpected error occurred when trying to symlink dotfiles.$NORMAL"
+    exit 1
+  fi
+  echo "${BOLD}To enable zsh, please execute 'chsh'.$NORMAL"
 }
 
 powerline_fonts() {
@@ -128,7 +158,7 @@ powerline_fonts() {
 # main
 # --------------
 main() {
-  echo -n "${BOLD}command: ${NORMAL}"
+  echo -n "${BOLD}command: $NORMAL"
   read command
   case $command in
     init)
@@ -147,7 +177,7 @@ main() {
       ln -s ${HOME}/.zplug ${ROOT_HOME}/.zplug
       ;;
     *)
-      echo "${RED}bootstrap: command not found.${NORMAL}"
+      echo "${RED}bootstrap: command not found.$NORMAL"
       exit 1
       ;;
   esac
